version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app:app --host 0.0.0.0 --port 8080
    env_file: .env
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - "./src:/code"
    networks:
      bewise:
        aliases:
          - bewise-backend

  postgres:
    image: postgres
    env_file: .env
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - "./postgres_data:/var/lib/postgresql/data"
    networks:
      bewise:
        aliases:
          - bewise-postgres

networks:
  bewise:
    external: true
